// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_XgKnDwZRZDZKosVm2hv_LD3jB_iyvY',
    appId: '1:910053826250:web:23106ea11ee40db8d01e33',
    messagingSenderId: '910053826250',
    projectId: 'birdapp-df9ed',
    authDomain: 'birdapp-df9ed.firebaseapp.com',
    storageBucket: 'birdapp-df9ed.firebasestorage.app',
    measurementId: 'G-PJRV358TXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW7K4Ue230fFZZc6JNuyU5q8WcMIOHpiM',
    appId: '1:910053826250:android:bb078aeb59fcbd1cd01e33',
    messagingSenderId: '910053826250',
    projectId: 'birdapp-df9ed',
    storageBucket: 'birdapp-df9ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBHVJrSGIb5YewwTXuU9eIUXHT5MrEVF8',
    appId: '1:910053826250:ios:bec56972001e8356d01e33',
    messagingSenderId: '910053826250',
    projectId: 'birdapp-df9ed',
    storageBucket: 'birdapp-df9ed.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBHVJrSGIb5YewwTXuU9eIUXHT5MrEVF8',
    appId: '1:910053826250:ios:bec56972001e8356d01e33',
    messagingSenderId: '910053826250',
    projectId: 'birdapp-df9ed',
    storageBucket: 'birdapp-df9ed.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX_XgKnDwZRZDZKosVm2hv_LD3jB_iyvY',
    appId: '1:910053826250:web:7114e82c8b9d24c3d01e33',
    messagingSenderId: '910053826250',
    projectId: 'birdapp-df9ed',
    authDomain: 'birdapp-df9ed.firebaseapp.com',
    storageBucket: 'birdapp-df9ed.firebasestorage.app',
    measurementId: 'G-VBND54C0RQ',
  );

}